"use client";
import {useEffect,useMemo,useState} from "react";
import {toast} from "sonner";
import {Archive,CheckCircle2,Cloud,Database,Download,FileArchive,HardDrive,History,RefreshCw,RotateCcw,Save,ShieldAlert,ShieldCheck,Trash2,Upload} from "lucide-react";
import {ActionButton,ErrorBox,Field,Loading,api,date,useData} from "@/lib/client";
import {Dialog,DialogContent,DialogHeader,DialogTitle} from "@/components/ui/dialog";

const sections=[
  ["backup-restore","Backup & Restore"],["history","Backup History"],["scheduled","Scheduled Backups"],
  ["storage","Google Drive / External Storage"],["import-export","Import / Export"],["migration","Migration Package"],
  ["health","Backup Health"],["source-code","Source Code Backup Status"],
];
const kinds=[
  ["full","Full Backup","Data, settings, theme, SEO and verified media copies"],
  ["data","Data / Database","Content, exams, commerce and SEO records"],
  ["media","Media Backup","Actual uploaded images, PDFs and attachments"],
  ["settings","Settings Backup","Admin-created configuration and roles mapping"],
  ["theme","Theme Backup","Homepage, theme, header, footer and navigation"],
  ["exam","Exam Backup","Packages, exams, questions, answers and access codes"],
  ["commerce","Commerce Backup","Orders, coupons, payments and pricing data"],
  ["recovery","Recovery Snapshot","A manual safety point before major work"],
];
const moduleLabels:Record<string,string>={content:"Books, Notes, Notices, Courses & Blog",exams:"Exams, Questions, Answers & Codes",commerce:"Commerce",settings:"Settings & Roles",theme:"Homepage, Theme, Header, Footer & Navigation",seo:"SEO",media:"Actual Media Files"};
const bytes=(n:number)=>n<1024?`${n||0} B`:n<1048576?`${(n/1024).toFixed(1)} KB`:`${(n/1048576).toFixed(1)} MB`;
const statusClass=(status:string)=>status==="verified"||status==="healthy"||status==="synced"||status==="connected"?"good":status==="failed"||status==="critical"?"critical":"warning";
const Status=({value}:any)=><span className={`backup-status ${statusClass(value)}`}>{value==="verified"||value==="healthy"||value==="synced"||value==="connected"?<CheckCircle2/>:value==="failed"||value==="critical"?<ShieldAlert/>:<RefreshCw/>}{String(value||"pending").replaceAll("_"," ")}</span>;
const manifest=(row:any)=>{try{return typeof row.manifest==="string"?JSON.parse(row.manifest):row.manifest||{}}catch{return {}}};

export function BackupCenter({section="backup-restore"}:{section?:string}){
  const {data,error,reload}=useData("admin/backup/overview");
  const [restore,setRestore]=useState<any>(null),[selected,setSelected]=useState<string[]>([]),[file,setFile]=useState<File|null>(null),[importPack,setImportPack]=useState<any>(null);
  const current=sections.some(x=>x[0]===section)?section:"backup-restore";
  useEffect(()=>{setRestore(null)},[current]);
  const create=async(kind:string)=>{const result=await api("admin/backup/create",{kind});reload();toast.success(result.driveStatus==="synced"?"Backup verified and copied to Google Drive":"Backup verified in site storage. Check Google Drive status separately.");return result};
  const beginRestore=(row:any)=>{const modules=manifest(row).includedModules||[];setSelected(modules);setRestore(row)};
  const toggle=(name:string)=>setSelected(selected.includes(name)?selected.filter(x=>x!==name):[...selected,name]);
  if(!data)return <><ErrorBox error={error}/>{!error&&<Loading/>}</>;
  const drive=data.storage.find((x:any)=>x.provider==="google_drive")||{};
  return <>
    <div className="cc-heading backup-heading"><div><div className="eyebrow">SYSTEM · RECOVERY CENTER</div><h1>{sections.find(x=>x[0]===current)?.[1]}</h1><p>Verified, recoverable backups with protected restore steps and clear source-of-truth status.</p></div><div className="cc-actions"><ActionButton action={()=>create("full")}><Archive size={16}/> Create Full Backup</ActionButton></div></div>
    <nav className="backup-nav" aria-label="Backup sections">{sections.map(([id,label])=><a key={id} className={id===current?"active":""} href={`/admin/system/${id}`}>{label}</a>)}</nav>
    <ErrorBox error={error}/>
    {current==="backup-restore"&&<Overview data={data} create={create} restore={beginRestore} reload={reload}/>}
    {current==="history"&&<HistoryView rows={data.history} reload={reload} restore={beginRestore} driveConnected={!!drive.connected}/>}
    {current==="scheduled"&&<Schedules rows={data.schedules} reload={reload}/>} 
    {current==="storage"&&<Storage connection={drive} configured={data.googleDriveConfigured} redirectUri={data.googleDriveRedirectUri} history={data.history} reload={reload}/>}
    {current==="import-export"&&<ImportExport file={file} setFile={setFile} pack={importPack} setPack={setImportPack} reload={reload}/>} 
    {current==="migration"&&<Migration create={create} rows={data.history}/>} 
    {current==="health"&&<Health data={data}/>} 
    {current==="source-code"&&<SourceCode status={data.sourceCode}/>} 
    <Dialog open={!!restore} onOpenChange={v=>!v&&setRestore(null)}><DialogContent className="backup-restore-dialog"><DialogHeader><DialogTitle>Safe restore</DialogTitle></DialogHeader>{restore&&<div><div className="backup-flow"><span>1. Verify</span><span>2. Recovery snapshot</span><span>3. Restore</span><span>4. Verify result</span></div><p className="backup-caution">This restores the selected records to their backed-up values. A verified pre-restore backup is created automatically. Existing unrelated records are preserved.</p><div className="backup-module-grid">{(manifest(restore).includedModules||[]).map((name:string)=><label key={name}><input type="checkbox" checked={selected.includes(name)} onChange={()=>toggle(name)}/><span><b>{moduleLabels[name]||name}</b><small>{name==="media"?"Copies actual stored files back to their original keys.":"Restores portable database records."}</small></span></label>)}</div><ActionButton disabled={!selected.length} action={async()=>{const confirmation=window.prompt('Type RESTORE to continue');if(confirmation!=="RESTORE")throw Error("Restore cancelled. The confirmation text did not match.");const result=await api(`admin/backup/${restore.id}/restore`,{modules:selected,confirmation:"RESTORE"});setRestore(null);reload();toast.success(`Restore verified. Recovery snapshot: ${result.recoveryBackupId}`)}}><RotateCcw size={16}/> Verify & Restore Selected</ActionButton></div>}</DialogContent></Dialog>
  </>;
}

function Overview({data,create,restore,reload}:any){
  const recent=data.history.slice(0,5),driveConnected=!!data.storage.find((x:any)=>x.provider==="google_drive")?.connected;
  return <>
    <div className="backup-health-card"><div><ShieldCheck/><span><small>BACKUP HEALTH</small><strong>{data.health.status}</strong></span></div><Status value={data.health.status}/><dl><div><dt>Last full</dt><dd>{date(data.health.lastFullBackup)}</dd></div><div><dt>Last verified</dt><dd>{date(data.health.lastVerifiedBackup)}</dd></div><div><dt>Last Drive copy</dt><dd>{date(data.health.lastDriveBackup)}</dd></div><div><dt>Next planned</dt><dd>{date(Number.isFinite(data.health.nextScheduledBackup)?data.health.nextScheduledBackup:null)}</dd></div></dl></div>
    <div className="backup-next-actions">{!driveConnected&&<a href="/admin/system/storage"><Cloud size={20}/><span><b>Connect Google Drive</b><small>Authorize a destination for verified off-site copies.</small></span></a>}{!data.health.automaticSchedulesAvailable&&<a href="/admin/system/scheduled"><RefreshCw size={20}/><span><b>Scheduling needs a trigger</b><small>Saved schedules do not run unattended until hosting is configured.</small></span></a>}</div>
    <section className="card cc-panel"><h2><FileArchive size={20}/> Create a backup</h2><div className="backup-kind-grid">{kinds.map(([id,title,description])=><article key={id}><span className="backup-kind-icon">{id==="media"?<HardDrive/>:id==="data"?<Database/>:<Archive/>}</span><b>{title}</b><p>{description}</p><ActionButton className="btn secondary small" action={()=>create(id)}>Create & Verify</ActionButton></article>)}</div></section>
    <section className="card cc-panel"><div className="cc-panel-title"><h2><History size={19}/> Recent backups</h2><a href="/admin/system/history">View all</a></div><BackupTable rows={recent} restore={restore} driveConnected={driveConnected} reload={reload}/></section>
  </>;
}

function BackupTable({rows,restore,reload,driveConnected}:any){
  if(!rows.length)return <p className="muted">No backups have been created yet.</p>;
  return <div className="backup-table"><div className="backup-table-head"><span>Date</span><span>Type / Size</span><span>Status</span><span>Google Drive</span><span>Actions</span></div>{rows.map((row:any)=>{
    const valid=row.status==="verified"&&row.verification_status==="verified"&&!!row.archive_key;
    return <div className="backup-table-row" key={row.id}><span><b>{date(row.created_at)}</b><small>{row.source?.replaceAll("_"," ")} · {row.created_by}</small></span><span><b>{row.kind.replaceAll("_"," ")}</b><small>{bytes(row.size_bytes)} · {row.media_count||0} files</small></span><span><Status value={row.verification_status}/>{row.error_message&&<small className="backup-error">{row.error_message}</small>}</span><span><Status value={row.drive_status}/>{row.drive_error_message&&<small className="backup-error">{row.drive_error_message}</small>}{row.drive_status==="synced"&&row.drive_folder_id&&<a className="backup-drive-link" href={`https://drive.google.com/drive/u/0/folders/${encodeURIComponent(row.drive_folder_id)}`} target="_blank" rel="noreferrer">Open folder</a>}</span><span className="backup-row-actions">{valid&&<><a className="icon-btn" href={`/api/admin/backup/${row.id}/download`} title="Download verified backup"><Download size={15}/></a><button className="icon-btn" title="Restore" onClick={()=>restore(row)}><RotateCcw size={15}/></button>{driveConnected&&row.drive_status!=="synced"&&<ActionButton className="btn secondary small" action={async()=>{const result=await api(`admin/backup/${row.id}/drive`,{});reload();toast.success(`Copied ${result.fileCount} files to Google Drive`)}}>Copy to Drive</ActionButton>}</>}{reload&&<><ActionButton className="icon-btn" title="Verify" action={async()=>{await api(`admin/backup/${row.id}/verify`,{});reload();toast.success("Backup verified")}}><ShieldCheck size={15}/></ActionButton><ActionButton className={`icon-btn ${row.keep_forever?"active":""}`} title={row.keep_forever?"Remove Keep Forever":"Keep Forever"} action={async()=>{await api(`admin/backup/${row.id}/keep`,{keepForever:!row.keep_forever},"PATCH");reload()}}><Save size={15}/></ActionButton><ActionButton className="icon-btn danger" title="Delete local backup" action={async()=>{if(!window.confirm("Delete this local backup permanently? Any existing Google Drive copy will remain."))return;await api(`admin/backup/${row.id}`,{confirmation:"DELETE"},"DELETE");reload();toast.success("Local backup deleted")}}><Trash2 size={15}/></ActionButton></>}</span></div>
  })}</div>;
}
function HistoryView({rows,reload,restore,driveConnected}:any){return <section className="card cc-panel"><div className="backup-panel-note"><ShieldCheck/><span><b>Verified backups can be restored or copied to Drive.</b><small>Deleting a local backup leaves any Google Drive copy in place.</small></span></div><BackupTable rows={rows} reload={reload} restore={restore} driveConnected={driveConnected}/></section>}
function Schedules({rows,reload}:any){return <><section className="card cc-panel"><h2><RefreshCw size={20}/> Backup schedule</h2><p className="backup-error">Automatic execution requires a hosting scheduler. These saved preferences cannot run on their own. Use Run now in the meantime.</p><div className="backup-schedule-list">{rows.map((row:any)=><article key={row.id}><div><b>{row.label}</b><small>{row.backup_type} · last run {date(row.last_run_at)} · planned {date(row.next_run_at)}</small>{row.enabled&&row.next_run_at<Date.now()&&<small className="backup-error">Planned time has passed without a run.</small>}</div><Field label="Keep latest"><input type="number" min="1" max="120" defaultValue={row.retention_count} onBlur={async e=>{await api(`admin/backup/schedule/${row.id}`,{enabled:!!row.enabled,retentionCount:Number(e.target.value)},"PATCH");reload()}}/></Field><span>Saved preference: {row.enabled?"On":"Off"}</span><ActionButton className="btn secondary small" action={async()=>{await api(`admin/backup/schedule/${row.id}/run`,{});reload();toast.success("Backup created and verified")}}>Run now</ActionButton></article>)}</div></section></>}

function Storage({connection,configured,redirectUri,history,reload}:any){
  const [form,setForm]=useState({accountEmail:connection.account_email||"",folder:connection.folder||"LexVeritas Academy Backups/"});
  const result=typeof window!=="undefined"?new URLSearchParams(window.location.search).get("drive"):null;
  const pending=history.filter((x:any)=>x.status==="verified"&&x.verification_status==="verified"&&x.drive_status!=="synced").length;
  return <><div className="backup-storage-summary"><article><small>GOOGLE ACCOUNT</small><strong>{connection.account_email||"Not selected"}</strong><Status value={connection.status}/></article><article><small>LAST SUCCESSFUL COPY</small><strong>{date(connection.last_synced_at)}</strong></article><article><small>WAITING TO COPY</small><strong>{pending}</strong></article></div>
    {result&&<p className={result==="connected"?"notice success":"backup-error"}>{result==="connected"?"Google Drive is connected. Sync the existing backups below.":`Google authorization did not complete: ${result.replaceAll("_"," ")}.`}</p>}
    <div className="cc-split"><section className="card cc-panel"><div className="backup-storage-title"><Cloud/><span><h2>Google Drive connection</h2><Status value={connection.status}/></span></div>
      <p>Use a dedicated folder in your Google Drive. LexVeritas requests permission only for files it creates. Each verified backup is copied as one TAR archive containing the data package and its media files. Originals remain in site storage.</p>
      <Field label="Google account email"><input type="email" value={form.accountEmail} onChange={e=>setForm({...form,accountEmail:e.target.value})}/></Field>
      <Field label="Backup folder"><input value={form.folder} onChange={e=>setForm({...form,folder:e.target.value})}/></Field>
      <div className="cc-actions left"><ActionButton action={async()=>{const response=await api(`admin/backup/storage/${connection.id}`,form,"PATCH");reload();toast.success(response.message)}}><Save size={16}/> Save destination</ActionButton>
      {configured&&<ActionButton className="btn secondary" action={async()=>{const response=await api(`admin/backup/storage/${connection.id}/connect`,{});const url=new URL(response.authorizationUrl);if(url.origin!=="https://accounts.google.com")throw Error("Unexpected authorization destination");window.location.href=url.toString()}}>Connect Google Drive</ActionButton>}
      {!!connection.connected&&<><ActionButton className="btn secondary" action={async()=>{const response=await api(`admin/backup/storage/${connection.id}/test`,{});reload();toast.success(`Connected as ${response.email}`)}}>Test connection</ActionButton><ActionButton className="btn" action={async()=>{const response=await api(`admin/backup/storage/${connection.id}/sync`,{});reload();toast.info(`${response.results.filter((x:any)=>x.driveStatus==="synced").length} copied · ${response.remaining} remain`)}}>Copy pending backups</ActionButton></>}</div>
      {!configured&&<p className="backup-disclosure">Google OAuth setup is needed before authorization. Add GOOGLE_OAUTH_CLIENT_ID and GOOGLE_OAUTH_CLIENT_SECRET as site runtime settings. Authorized redirect URI: <code>{redirectUri}</code>. The backup encryption key is managed separately as a secret.</p>}
    </section><section className="card cc-panel"><h2>How the copy works</h2><ol className="backup-steps"><li>Save the destination and authorize the selected Google account.</li><li>Test the connection, then copy existing verified backups.</li><li>New backups copy automatically after local verification. Failures leave the local backup available for retry.</li></ol><a className="btn secondary" href="/admin/system/history">Open Backup History</a></section></div>
  </>;
}

function ImportExport({file,setFile,pack,setPack,reload}:any){const inspect=async(f:File|null)=>{setFile(f);setPack(null);if(!f)return;if(f.size>12000000)throw Error("Choose a JSON package smaller than 12 MB.");const parsed=JSON.parse(await f.text());if(parsed.format!=="lexveritas-backup-package"||parsed.version!==3)throw Error("Extract lexveritas-backup.json from the downloaded archive and choose it here.");const preview=await api("admin/backup/import-preview",parsed);setPack({...parsed,__preview:preview})};return <div className="cc-split"><section className="card cc-panel"><Upload size={34}/><h2>Import backup</h2><p>Extract lexveritas-backup.json from a downloaded TAR.GZ archive, then validate its checksum and conflicts. A full recovery snapshot is created automatically and live records are never silently deleted.</p><input type="file" accept="application/json,.json" onChange={e=>inspect(e.target.files?.[0]||null).catch(x=>toast.error(x.message))}/>{pack&&<div className="backup-import-preview"><b>{pack.manifest.type} · {pack.manifest.backupId}</b><span>{date(pack.manifest.createdAt)} · {pack.manifest.mediaCount||0} media references</span><span><b>{pack.__preview.newRecords}</b> new records · <b>{pack.__preview.conflictingRecords}</b> existing records will be updated</span>{pack.__preview.conflictingRecords>0&&<small>Conflicts: {Object.entries(pack.__preview.conflicts).map(([key,value])=>`${key} (${value})`).join(", ")}</small>}<div>{(pack.manifest.includedModules||[]).map((x:string)=><em key={x}>{x}</em>)}</div></div>}<ActionButton disabled={!file||!pack} action={async()=>{if(!window.confirm("Import this validated package? Existing matching records will be updated and a recovery snapshot will be created first."))return;const result=await api("admin/backup/import",pack);reload();toast.success(`Imported ${result.imported} records. Recovery: ${result.recoveryBackupId}`)}}>Validate, Snapshot & Import</ActionButton></section><section className="card cc-panel"><Download size={34}/><h2>Export options</h2><p>Use Backup History to download a verified TAR.GZ archive containing the portable JSON package, migration README, checksums and actual media files.</p><a className="btn" href="/admin/system/history">Open Backup History</a><p className="backup-disclosure">Media is streamed into the archive instead of being embedded as base64, keeping exports portable without unsafe memory duplication.</p></section></div>}
function Migration({create,rows}:any){const latest=rows.find((x:any)=>x.kind==="migration"&&x.status==="verified");return <section className="card cc-panel migration-panel"><FileArchive size={44}/><div><h2>Portable Migration Package</h2><p>Creates portable data, route/content records, design settings, navigation, SEO, schema inventory, media manifest, checksums and a migration README. Actual media files are copied into the same protected backup folder.</p><ul><li>JSON data export with module and table counts</li><li>Actual R2 media copies with size verification</li><li>No passwords, sessions, OAuth credentials or payment-card data</li><li>No automatic slug or route changes</li></ul>{latest&&<p><b>Latest package:</b> {date(latest.created_at)} · {bytes(latest.size_bytes)}</p>}<ActionButton action={()=>create("migration")}><Archive size={16}/> Create Migration Package</ActionButton></div></section>}
function Health({data}:any){return <><div className="backup-health-card compact"><div><ShieldCheck/><span><small>OVERALL STATUS</small><strong>{data.health.status}</strong></span></div><Status value={data.health.status}/></div><div className="backup-health-grid">{[["Last full backup",date(data.health.lastFullBackup),!!data.health.lastFullBackup],["Last verified backup",date(data.health.lastVerifiedBackup),!!data.health.lastVerifiedBackup],["Last Google Drive backup",date(data.health.lastDriveBackup),!!data.health.lastDriveBackup],["Next planned backup",date(Number.isFinite(data.health.nextScheduledBackup)?data.health.nextScheduledBackup:null),!!data.health.automaticSchedulesAvailable],["Drive status",data.health.driveStatus,data.health.driveStatus==="connected"],["Failed backups",String(data.health.failed),data.health.failed===0]].map(([label,value,good]:any)=><article className="card" key={label}><span>{label}</span><b>{value}</b><Status value={good?"healthy":label==="Failed backups"&&Number(value)>0?"critical":"warning"}/></article>)}</div></>}
function SourceCode({status}:any){return <section className="card cc-panel"><div className="backup-panel-note"><ShieldAlert/><span><b>Source code is separate from content backups.</b><small>The Admin Panel never labels a data/media package as a source-code backup.</small></span></div><div className="source-status-list">{Object.entries(status).map(([key,value]:any)=><div key={key}><span><b>{key.replace(/([A-Z])/g," $1")}</b><small>{String(value)}</small></span><Status value={value===false||String(value).startsWith("Not available")?"warning":"healthy"}/></div>)}</div></section>}
