"use client";

import { useEffect, useMemo, useState } from "react";
import { BookOpen, Check, CheckCircle2, ChevronDown, ChevronLeft, ChevronRight, CirclePlay, FileText, ListChecks, LockKeyhole, Menu, Maximize2, X, ZoomIn, ZoomOut } from "lucide-react";
import { Progress } from "@/components/ui/progress";
import { Sheet, SheetContent, SheetHeader, SheetTitle, SheetTrigger } from "@/components/ui/sheet";
import { api, ErrorBox, Loading } from "@/lib/client";

const parse=(v:any,f:any=[])=>{try{return typeof v==="string"?JSON.parse(v):v??f}catch{return f}};

export function CourseLearning({courseId}:{courseId:string}){
  const [data,setData]=useState<any>(null),[error,setError]=useState(""),[code,setCode]=useState(""),[busy,setBusy]=useState(false),[current,setCurrent]=useState(""),[drawer,setDrawer]=useState(false);
  const load=async()=>{try{const d=await api(`course-learning/${courseId}`);setData(d);setCurrent((v)=>v||d.last_accessed_lesson||d.content.find((x:any)=>x.node_type==="lesson"&&!x.locked)?.id||"");setError("")}catch(e:any){setError(e.message)}};
  useEffect(()=>{load()},[courseId]);
  if(!data&&!error)return <Loading/>;
  if(!data)return <div className="container section"><ErrorBox error={error}/><div className="course-access-card card"><LockKeyhole size={42}/><h1>Open Your Course</h1><p>Enter the access code issued after your course payment was verified.</p><form onSubmit={async e=>{e.preventDefault();setBusy(true);try{await api(`course-learning/${courseId}/access`,{code});await load()}catch(x:any){setError(x.message)}finally{setBusy(false)}}}><input value={code} onChange={e=>setCode(e.target.value.toUpperCase())} placeholder="LVA-XXXX-XXXX-XXXX" required/><button className="btn" disabled={busy}>{busy?"Checking…":"Open Course"}</button></form></div></div>;
  const lessons=data.content.filter((x:any)=>x.node_type==="lesson"&&x.status==="published"),active=lessons.find((x:any)=>x.id===current)||lessons[0],index=Math.max(0,lessons.findIndex((x:any)=>x.id===active?.id)),completed=new Set(data.completed_ids||[]),progress=lessons.length?Math.round(completed.size/lessons.length*100):0;
  const unlock=async(e:any)=>{e.preventDefault();setBusy(true);try{await api(`course-learning/${courseId}/access`,{code});await load();setError("")}catch(x:any){setError(x.message)}finally{setBusy(false)}};
  const select=(id:string)=>{setCurrent(id);setDrawer(false)};
  const mark=async()=>{if(!active||active.locked)return;await api(`course-learning/${courseId}/progress`,{contentId:active.id,completed:true});setData((d:any)=>({...d,completed_ids:[...new Set([...(d.completed_ids||[]),active.id])]}))};
  const sidebar=<Curriculum data={data} current={active?.id} completed={completed} select={select}/>;
  return <div className="learning-shell"><header className="learning-header"><a href={`/courses/${courseId}`}><ChevronLeft/> Course Details</a><div><b>{data.course.name}</b><span>{progress}% complete</span></div><Progress value={progress}/><Sheet open={drawer} onOpenChange={setDrawer}><SheetTrigger className="learning-menu"><Menu/> Curriculum</SheetTrigger><SheetContent className="learning-drawer"><SheetHeader><SheetTitle>Course Curriculum</SheetTitle></SheetHeader>{sidebar}</SheetContent></Sheet></header>{!data.authorized&&data.content.some((x:any)=>x.node_type==="lesson"&&x.locked)&&<form className="learning-unlock" onSubmit={unlock}><LockKeyhole/><span><b>Enrolled student?</b> Enter your access code to unlock the full course.</span><input value={code} onChange={e=>setCode(e.target.value.toUpperCase())} placeholder="LVA-XXXX-XXXX-XXXX" required/><button className="btn" disabled={busy}>{busy?"Checking…":"Unlock Course"}</button>{error&&<small>{error}</small>}</form>}<div className="learning-layout"><main className="learning-main">{active?<><LessonBody courseId={courseId} lesson={active}/><section className="learning-copy"><div className="eyebrow">CURRENT LESSON</div><h1>{active.title}</h1><p>{active.description}</p>{!active.locked&&active.exam_id&&active.lesson_type!=="exam"&&<div className="exam-launch"><ListChecks/><h2>Class examination</h2><a className="btn" href={`/exams/${active.exam_id}?course=${courseId}`} target="_blank">Open linked MCQ exam</a></div>}{parse(active.resources).length>0&&<div className="lesson-resources"><h2>Resources</h2>{parse(active.resources).map((r:any)=><a key={r.id} href={`/api/course-learning/${courseId}/content/${active.id}/resource/${r.id}`} target="_blank"><FileText/>{r.title||"Supporting PDF"}{r.download_allowed&&<span>Download allowed</span>}</a>)}</div>}<div className="learning-actions"><button disabled={index<=0} onClick={()=>select(lessons[index-1]?.id)}><ChevronLeft/> Previous Lesson</button><button className="complete" disabled={completed.has(active.id)||active.locked||!data.authorized} onClick={mark}><CheckCircle2/> {completed.has(active.id)?"Completed":"Mark as Complete"}</button><button disabled={index>=lessons.length-1} onClick={()=>select(lessons[index+1]?.id)}>Next Lesson <ChevronRight/></button></div></section></>:<div className="editor-empty"><BookOpen/><h1>No published lessons yet</h1></div>}</main><aside className="learning-sidebar">{sidebar}</aside></div></div>;
}
function Curriculum({data,current,completed,select}:any){
  const modules=data.content.filter((x:any)=>x.node_type==="module"&&x.status==="published");
  const lessonButton=(l:any)=><button key={l.id} className={current===l.id?"active":""} disabled={l.locked} onClick={()=>select(l.id)}><span>{l.locked?<LockKeyhole/>:completed.has(l.id)?<Check/>:l.lesson_type==="youtube"||l.lesson_type==="video"?<CirclePlay/>:l.lesson_type==="exam"?<ListChecks/>:<FileText/>}</span><span>{l.title}<small>{l.locked?"Code required":l.lesson_type?.replaceAll("_"," ")}</small></span></button>;
  return <div className="student-curriculum"><div className="curriculum-progress"><b>Course Progress</b><span>{data.progress_percent||0}%</span></div>{modules.map((m:any)=><details key={m.id} open><summary>{m.title}<ChevronDown/></summary>{data.content.filter((x:any)=>x.parent_id===m.id).sort((a:any,b:any)=>a.display_order-b.display_order).map((item:any)=>item.node_type==="lesson"?lessonButton(item):item.node_type==="chapter"?<div className="student-chapter" key={item.id}><h3>{item.title}</h3>{data.content.filter((x:any)=>x.parent_id===item.id&&x.node_type==="lesson").sort((a:any,b:any)=>a.display_order-b.display_order).map(lessonButton)}</div>:null)}</details>)}</div>;
}
function LessonBody({courseId,lesson}:any){if(lesson.locked)return <div className="lesson-locked"><LockKeyhole/><h2>This lesson is locked</h2><p>Complete the required lesson or progress milestone first.</p></div>;if(lesson.lesson_type==="youtube"&&lesson.video_id)return <div className="learning-video"><iframe src={`https://www.youtube-nocookie.com/embed/${lesson.video_id}?rel=0`} title={lesson.title} allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowFullScreen/></div>;if(lesson.lesson_type==="video"&&lesson.video_url)return <div className="learning-video"><video src={lesson.video_url} controls playsInline/></div>;if((lesson.lesson_type==="pdf"||lesson.lesson_type==="notes")&&lesson.file_id)return <PdfLesson src={`/api/course-learning/${courseId}/content/${lesson.id}/file`} title={lesson.title}/>;if(lesson.lesson_type==="exam"&&lesson.exam_id)return <div className="exam-launch"><ListChecks/><h2>{lesson.title}</h2><p>Open the connected MCQ examination when you are ready.</p><a className="btn" href={`/exams/${lesson.exam_id}?course=${courseId}`} target="_blank">Start Exam</a></div>;if(lesson.lesson_type==="package"&&lesson.package_id)return <div className="exam-launch"><ListChecks/><h2>{lesson.title}</h2><p>This lesson includes an existing exam package.</p><a className="btn" href={`/packages/${lesson.package_id}`} target="_blank">Open Exam Package</a></div>;if(lesson.lesson_type==="resource"&&lesson.external_url)return <div className="exam-launch"><FileText/><h2>{lesson.title}</h2><a className="btn" href={lesson.external_url} target="_blank" rel="noopener noreferrer">Open Resource</a></div>;return <article className="text-lesson"><FileText/><div style={{whiteSpace:"pre-wrap"}}>{lesson.body||""}</div></article>}
function PdfLesson({src,title}:any){const [zoom,setZoom]=useState(100),[full,setFull]=useState(false);return <div className={`course-pdf ${full?"fullscreen":""}`}><div className="course-pdf-toolbar"><b>{title}</b><div><button onClick={()=>setZoom(Math.max(75,zoom-25))}><ZoomOut/></button><span>{zoom}%</span><button onClick={()=>setZoom(Math.min(200,zoom+25))}><ZoomIn/></button><button onClick={()=>setFull(!full)}>{full?<X/>:<Maximize2/>}</button></div></div><div className="course-pdf-scroll"><iframe src={`${src}#toolbar=0&navpanes=0&zoom=${zoom}`} title={title} style={{width:`${zoom}%`}}/></div></div>}
