"use client";

import { useEffect, useMemo, useState } from "react";
import {
  ArrowDown, ArrowLeft, ArrowUp, BookOpen, Check, ChevronDown, ChevronRight,
  CirclePlay, Copy, Eye, FileText, FolderPlus, GripVertical, Layers3, Link2,
  ListChecks, Monitor, MoreVertical, Pencil, Plus, Save, Smartphone, Tablet,
  Trash2, UploadCloud, Video,
} from "lucide-react";
import { toast } from "sonner";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Switch } from "@/components/ui/switch";
import { Progress } from "@/components/ui/progress";
import { MediaUpload } from "./media-upload";
import { AccessCodesPanel } from "./access-codes";
import { api, cash, ErrorBox, Field, Loading, money, useData } from "@/lib/client";

type NodeType = "module" | "chapter" | "lesson";
type LessonType = "youtube" | "video" | "pdf" | "notes" | "exam" | "package" | "text" | "resource";
type Node = {
  id: string; parent_id: string | null; node_type: NodeType; lesson_type?: LessonType | null;
  title: string; description: string; body: string; video_url?: string; video_id?: string;
  video_duration?: string; thumbnail?: string | null; instructor?: string; file_id?: string | null;
  resources: any[]; exam_id?: string | null; package_id?: string | null; external_url?: string;
  status: "published" | "draft" | "hidden"; free_preview: boolean; download_allowed: boolean;
  access_mode:"public"|"code";
  unlock_rule: string; unlock_value: string; attempts_allowed: number; display_order: number;
};

const blankCourse = {
  name: "", description: "", full_description: "", category: "", subject: "", instructor: "",
  thumbnail: null, regular_price: "", price: "0", pricing_type: "paid", duration_label: "",
  access_validity_days: 365, access_mode:"mixed", enrollment_start: "", course_start: "", course_end: "",
  maximum_students: "", enrollment_open: true, featured: false, status: "draft",
  sequential_learning: false, active: true, published: false, package_id: "", details: "",
};
const lessonLabels: Record<LessonType, string> = { youtube:"YouTube Video", video:"Hosted Video", pdf:"PDF / Lecture Sheet", notes:"Notes / Document", exam:"MCQ Exam", package:"Exam Package", text:"Text Lesson", resource:"External Resource" };
const newNode = (node_type: NodeType, parent_id: string | null, lesson_type?: LessonType): Node => ({
  id: crypto.randomUUID(), parent_id, node_type, lesson_type: lesson_type || null,
  title: node_type === "module" ? "New Module" : node_type === "chapter" ? "New Chapter" : `New ${lessonLabels[lesson_type || "text"]}`,
  description:"", body:"", resources:[], status:"published", free_preview:false, access_mode:"code", download_allowed:false,
  unlock_rule:"immediate", unlock_value:"", attempts_allowed:1, display_order:0,
});
const youtubeId = (value:string) => {
  try { const u=new URL(value.trim()); if(u.hostname.includes("youtu.be"))return u.pathname.split("/")[1]||""; if(u.pathname.startsWith("/shorts/"))return u.pathname.split("/")[2]||""; if(u.pathname.startsWith("/embed/"))return u.pathname.split("/")[2]||""; return u.searchParams.get("v")||""; } catch { return ""; }
};
const dt = (value:any) => value ? new Date(Number(value)).toISOString().slice(0,16) : "";
const ms = (value:string) => value ? new Date(value).getTime() : null;

export function CourseManager(){
  const {data,error}=useData("admin/courses");
  return <>
    <div className="section-head admin-page-heading"><div><div className="eyebrow">LEARNING MANAGEMENT</div><h1>Courses</h1><p>Create structured courses, connect exams, and control student access.</p></div><a className="btn" href="/admin/courses/new"><Plus size={17}/> Add Course</a></div>
    <ErrorBox error={error}/>{!data&&!error?<Loading/>:<div className="course-admin-grid">{data?.map((c:any)=><article className="card course-admin-card" key={c.id}>{c.thumbnail?<img src={`/api/files/${c.thumbnail}`} alt=""/>:<div className="course-admin-placeholder"><GraduationMark/></div>}<div><span className={`status-pill ${c.status||"draft"}`}>{c.status||"draft"}</span><h2>{c.name}</h2><p>{c.category||"Uncategorized"} · {c.instructor||"Instructor not set"}</p><div className="course-admin-meta"><span>{c.class_count||0} lessons</span><span>{money(c.price)}</span><span>{c.access_mode==="open"?"Open":c.access_mode==="mixed"?"Mixed access":"Code required"}</span></div><div className="course-admin-actions"><a className="btn" href={`/admin/courses/${c.id}`}><Pencil size={16}/> Edit Course</a><a className="btn outline" href={`/courses/${c.id}`} target="_blank"><Eye size={16}/> View</a></div></div></article>)}</div>}
  </>;
}
function GraduationMark(){return <BookOpen size={34}/>}

export function CourseBuilder({id}:{id?:string}){
  const endpoint=id?`admin/course-builder/${id}`:"admin/course-builder/new";
  const {data,error}=useData(endpoint),[course,setCourse]=useState<any>(blankCourse),[nodes,setNodes]=useState<Node[]>([]),[selected,setSelected]=useState<Node|null>(null),[contentChoice,setContentChoice]=useState<{parent:string}|null>(null),[expanded,setExpanded]=useState<Set<string>>(new Set()),[preview,setPreview]=useState<"desktop"|"tablet"|"mobile">("desktop"),[saving,setSaving]=useState(false),[youtubeWarning,setYoutubeWarning]=useState("");
  useEffect(()=>{if(!data)return;setCourse({...blankCourse,...data.course,price:String((data.course?.price||0)/100),regular_price:data.course?.regular_price==null?"":String(data.course.regular_price/100),enrollment_start:dt(data.course?.enrollment_start),course_start:dt(data.course?.course_start),course_end:dt(data.course?.course_end),maximum_students:data.course?.maximum_students??"",enrollment_open:!!data.course?.enrollment_open,featured:!!data.course?.featured,sequential_learning:!!data.course?.sequential_learning,active:!!data.course?.active,published:!!data.course?.published,package_id:data.course?.package_id||""});setNodes((data.content||[]).map((n:any)=>({...n,resources:parse(n.resources,[]),free_preview:!!n.free_preview,download_allowed:!!n.download_allowed})));setExpanded(new Set((data.content||[]).filter((x:any)=>x.node_type!=="lesson").map((x:any)=>x.id)));},[data]);
  const options=data?.options||{exams:[],packages:[]};
  const children=(parent:string|null)=>nodes.filter(n=>n.parent_id===parent).sort((a,b)=>a.display_order-b.display_order);
  const updateNode=(next:Node)=>{setNodes(v=>v.map(n=>n.id===next.id?next:n));setSelected(next)};
  const add=(type:NodeType,parent:string|null,lesson?:LessonType)=>{const n=newNode(type,parent,lesson);n.access_mode=nodes.find(x=>x.id===parent)?.access_mode|| (course.access_mode==="open"?"public":"code");n.display_order=children(parent).length+1;setNodes(v=>[...v,n]);setSelected(n);if(parent||type!=="lesson")setExpanded(v=>new Set([...v,...(parent?[parent]:[]),...(type!=="lesson"?[n.id]:[])]));setContentChoice(null)};
  const remove=(node:Node)=>{if(!confirm(`Delete “${node.title}” and everything inside it?`))return;const doomed=new Set([node.id]);let changed=true;while(changed){changed=false;for(const n of nodes)if(n.parent_id&&doomed.has(n.parent_id)&&!doomed.has(n.id)){doomed.add(n.id);changed=true}}setNodes(v=>v.filter(n=>!doomed.has(n.id)));if(selected&&doomed.has(selected.id))setSelected(null)};
  const duplicate=(node:Node)=>{const copies:Node[]=[];const walk=(original:Node,parent:string|null)=>{const copy:Node={...original,id:crypto.randomUUID(),parent_id:parent,title:original.id===node.id?`${original.title} (Copy)`:original.title,resources:(original.resources||[]).map((r:any)=>({...r,id:crypto.randomUUID()})),display_order:original.id===node.id?children(parent).length+1:original.display_order};copies.push(copy);for(const child of children(original.id))walk(child,copy.id)};walk(node,node.parent_id);setNodes(v=>[...v,...copies]);setSelected(copies[0]);setExpanded(v=>new Set([...v,...copies.filter(x=>x.node_type!=="lesson").map(x=>x.id)]))};
  const move=(node:Node,delta:number)=>{const siblings=children(node.parent_id),i=siblings.findIndex(n=>n.id===node.id),j=i+delta;if(j<0||j>=siblings.length)return;const a=siblings[i],b=siblings[j];setNodes(v=>v.map(n=>n.id===a.id?{...n,display_order:b.display_order}:n.id===b.id?{...n,display_order:a.display_order}:n))};
  const reorder=(sourceId:string,target:Node)=>{setNodes(current=>{const source=current.find(n=>n.id===sourceId);if(!source||source.id===target.id)return current;let parent=target.parent_id;if(target.node_type==="module"&&["chapter","lesson"].includes(source.node_type))parent=target.id;if(target.node_type==="chapter"&&source.node_type==="lesson")parent=target.id;if(source.node_type!==target.node_type&&parent===target.parent_id)return current;const order=target.display_order;return current.map(n=>n.id===source.id?{...n,parent_id:parent,display_order:order}:n.parent_id===parent&&n.id!==source.id&&n.display_order>=order?{...n,display_order:n.display_order+1}:n)});};
  const save=async(publish=false)=>{setSaving(true);try{const publishing=publish||course.status==="published";if(publishing&&!nodes.some(n=>n.node_type==="module"&&n.title.trim()&&n.title!=="New Module"))throw Error("Name at least one module before publishing the course.");const payload={course:{...course,price:cash(String(course.price||"0")),regular_price:course.regular_price===""?null:cash(String(course.regular_price)),enrollment_start:ms(course.enrollment_start),course_start:ms(course.course_start),course_end:ms(course.course_end),maximum_students:course.maximum_students===""?null:Number(course.maximum_students),status:publish?"published":course.status,published:publish?true:course.status==="published"},content:nodes.map(n=>({...n,resources:JSON.stringify(n.resources||[])}))};const result=await api(`admin/course-builder${id?`/${id}`:""}`,payload,id?"PATCH":"POST");toast.success(publish?"Course published":course.status==="published"?"Changes saved":"Draft saved");if(!id)window.location.href=`/admin/courses/${result.id}`;else if(publish)setCourse((c:any)=>({...c,status:"published",published:true}));}catch(e:any){toast.error(e.message||"Could not save the course.")}finally{setSaving(false)}};
  if(error)return <ErrorBox error={error}/>;if(!data)return <Loading/>;
  return <div className="course-builder">
    <div className="course-builder-head"><div><a href="/admin/courses" className="back-link"><ArrowLeft size={16}/> Courses</a><div className="eyebrow">LMS COURSE BUILDER</div><h1>{id?course.name||"Edit Course":"Add Course"}</h1></div><div className="builder-actions"><button className="btn outline" onClick={()=>save(false)} disabled={saving}><Save size={16}/> {course.status==="published"?"Save Changes":"Save Draft"}</button><button className="btn" onClick={()=>save(true)} disabled={saving}><Check size={16}/> Publish</button></div></div>
    <Tabs defaultValue="curriculum" className="course-builder-tabs"><TabsList><TabsTrigger value="basic">Basic Information</TabsTrigger><TabsTrigger value="curriculum">Curriculum Builder</TabsTrigger><TabsTrigger value="access">Access & Schedule</TabsTrigger><TabsTrigger value="preview">Student Preview</TabsTrigger></TabsList>
      <TabsContent value="basic"><BasicForm course={course} setCourse={setCourse}/></TabsContent>
      <TabsContent value="curriculum"><div className="builder-workspace"><section className="curriculum-panel"><div className="panel-title"><div><h2>Course Curriculum</h2><p>Name a module first, then add video, lecture and PDF lessons inside it. Chapters are optional.</p></div><button className="btn small" onClick={()=>add("module",null)}><FolderPlus size={16}/> Add Module</button></div><div className="curriculum-tree">{children(null).map(n=><TreeNode key={n.id} node={n} depth={0} {...{children,expanded,setExpanded,setSelected,selected,add,setContentChoice,duplicate,remove,move,reorder}}/>)}</div>{!children(null).length&&<button className="curriculum-empty" onClick={()=>add("module",null)}><Layers3/><b>Add your first module</b><span>Name it, then add videos, lectures and PDFs inside.</span></button>}</section><section className="lesson-editor">{selected?<NodeEditor node={selected} update={updateNode} options={options} youtubeWarning={youtubeWarning} setYoutubeWarning={setYoutubeWarning}/>:<div className="editor-empty"><Pencil size={32}/><h2>Select a module or lesson</h2><p>Start by adding and naming a module.</p></div>}</section></div></TabsContent>
      <TabsContent value="access"><AccessForm course={course} setCourse={setCourse}/>{id&&<AccessCodesPanel type="course" id={id}/>}</TabsContent>
      <TabsContent value="preview"><div className="preview-toolbar"><b>Student Preview</b><div><button className={preview==="desktop"?"active":""} onClick={()=>setPreview("desktop")}><Monitor/>Desktop</button><button className={preview==="tablet"?"active":""} onClick={()=>setPreview("tablet")}><Tablet/>Tablet</button><button className={preview==="mobile"?"active":""} onClick={()=>setPreview("mobile")}><Smartphone/>Mobile</button></div></div><CoursePreview course={course} nodes={nodes} mode={preview}/></TabsContent>
    </Tabs>
    <Dialog open={!!contentChoice} onOpenChange={v=>!v&&setContentChoice(null)}><DialogContent className="content-choice"><DialogHeader><DialogTitle>Add Lesson Content</DialogTitle></DialogHeader><div className="content-type-grid">{(Object.keys(lessonLabels) as LessonType[]).map(type=><button key={type} onClick={()=>add("lesson",contentChoice!.parent,type)}>{type==="youtube"||type==="video"?<CirclePlay/>:type==="exam"||type==="package"?<ListChecks/>:type==="resource"?<Link2/>:<FileText/>}<b>{lessonLabels[type]}</b></button>)}</div></DialogContent></Dialog>
  </div>;
}

function TreeNode({node,depth,children,expanded,setExpanded,setSelected,selected,add,setContentChoice,duplicate,remove,move,reorder}:any){const kids=children(node.id),open=expanded.has(node.id);return <div className="tree-wrap"><div className={`tree-row ${selected?.id===node.id?"selected":""}`} style={{paddingLeft:`${10+depth*20}px`}} draggable onDragStart={(e)=>e.dataTransfer.setData("text/plain",node.id)} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();const id=e.dataTransfer.getData("text/plain");if(id&&id!==node.id)reorder(id,node)}}><GripVertical className="drag-handle" size={16}/>{node.node_type!=="lesson"?<button className="tree-toggle" aria-label={`${open?"Collapse":"Expand"} ${node.title}`} onClick={()=>setExpanded((v:Set<string>)=>{const x=new Set(v);x.has(node.id)?x.delete(node.id):x.add(node.id);return x})}>{open?<ChevronDown/>:<ChevronRight/>}</button>:<span className="tree-icon">{node.lesson_type==="youtube"||node.lesson_type==="video"?<CirclePlay/>:node.lesson_type==="exam"||node.lesson_type==="package"?<ListChecks/>:<FileText/>}</span>}<button className="tree-label" onClick={()=>setSelected(node)}><b>{node.title}</b><small>{node.node_type==="lesson"?lessonLabels[node.lesson_type as LessonType]:node.node_type}</small></button><div className="tree-actions"><button title="Move up" onClick={()=>move(node,-1)}><ArrowUp/></button><button title="Move down" onClick={()=>move(node,1)}><ArrowDown/></button><button title="Duplicate" onClick={()=>duplicate(node)}><Copy/></button><button title="Delete" onClick={()=>remove(node)}><Trash2/></button></div></div>{open&&<div>{kids.map((n:any)=><TreeNode key={n.id} node={n} depth={depth+1} {...{children,expanded,setExpanded,setSelected,selected,add,setContentChoice,duplicate,remove,move,reorder}}/>)}{node.node_type==="module"&&<><button className="tree-add" style={{marginLeft:`${34+depth*20}px`}} onClick={()=>add("chapter",node.id)}><Plus/> Add Chapter</button><button className="tree-add" style={{marginLeft:`${34+depth*20}px`}} onClick={()=>add("lesson",node.id,"youtube")}><Plus/> Add Video</button><button className="tree-add" style={{marginLeft:`${34+depth*20}px`}} onClick={()=>add("lesson",node.id,"text")}><Plus/> Add Lecture</button><button className="tree-add" style={{marginLeft:`${34+depth*20}px`}} onClick={()=>add("lesson",node.id,"pdf")}><Plus/> Add PDF</button><button className="tree-add" style={{marginLeft:`${34+depth*20}px`}} onClick={()=>setContentChoice({parent:node.id})}><Plus/> Add Class</button></>}{node.node_type==="chapter"&&<button className="tree-add" style={{marginLeft:`${34+depth*20}px`}} onClick={()=>setContentChoice({parent:node.id})}><Plus/> Add Class</button>}</div>}</div>}

function BasicForm({course,setCourse}:any){const set=(k:string,v:any)=>setCourse((c:any)=>({...c,[k]:v}));return <div className="builder-form card"><div className="grid two"><Field label="Course Name"><input required value={course.name} onChange={e=>set("name",e.target.value)}/></Field><Field label="Category"><input value={course.category} onChange={e=>set("category",e.target.value)} placeholder="BJS / Bar Council / Law Officer"/></Field><Field label="Subject"><input value={course.subject} onChange={e=>set("subject",e.target.value)}/></Field><Field label="Instructor"><input value={course.instructor} onChange={e=>set("instructor",e.target.value)}/></Field></div><Field label="Short Description"><textarea rows={3} value={course.description} onChange={e=>set("description",e.target.value)}/></Field><Field label="Course Outline / Full Description"><textarea rows={8} value={course.full_description} onChange={e=>set("full_description",e.target.value)}/></Field><Field label="Course Thumbnail / Cover"><MediaUpload kind="course" value={course.thumbnail} onChange={v=>set("thumbnail",v)}/></Field><div className="grid three"><Field label="Pricing"><select value={course.pricing_type} onChange={e=>set("pricing_type",e.target.value)}><option value="paid">Paid</option><option value="free">Free</option></select></Field><Field label="Regular Price (BDT)"><input inputMode="decimal" value={course.regular_price} onChange={e=>set("regular_price",e.target.value)}/></Field><Field label="Discount / Current Price (BDT)"><input inputMode="decimal" value={course.price} onChange={e=>set("price",e.target.value)}/></Field><Field label="Course Duration"><input value={course.duration_label} onChange={e=>set("duration_label",e.target.value)} placeholder="12 weeks"/></Field><Field label="Access Validity (Days)"><input type="number" min="1" value={course.access_validity_days} onChange={e=>set("access_validity_days",Number(e.target.value))}/></Field><Field label="Maximum Students"><input type="number" min="1" value={course.maximum_students} onChange={e=>set("maximum_students",e.target.value)}/></Field></div><Toggle label="Featured Course" value={course.featured} set={(v:boolean)=>set("featured",v)}/></div>}
function AccessForm({course,setCourse}:any){const set=(k:string,v:any)=>setCourse((c:any)=>({...c,[k]:v}));return <div className="builder-form card"><Field label="Learner access"><select value={course.access_mode||"mixed"} onChange={e=>set("access_mode",e.target.value)}><option value="open">Open course · new classes public</option><option value="mixed">Mixed · set each class public or code</option><option value="code">Code required · new classes restricted</option></select></Field><p className="muted">Each class can override this default. Existing classes keep their own access setting.</p><div className="grid three"><Field label="Enrollment Start"><input type="datetime-local" value={course.enrollment_start} onChange={e=>set("enrollment_start",e.target.value)}/></Field><Field label="Course Start"><input type="datetime-local" value={course.course_start} onChange={e=>set("course_start",e.target.value)}/></Field><Field label="Course End"><input type="datetime-local" value={course.course_end} onChange={e=>set("course_end",e.target.value)}/></Field></div><div className="access-switches"><Toggle label="Enrollment Open" help="Students can place a new course order." value={course.enrollment_open} set={(v:boolean)=>set("enrollment_open",v)}/><Toggle label="Sequential Learning" help="Students complete lessons in order." value={course.sequential_learning} set={(v:boolean)=>set("sequential_learning",v)}/><Toggle label="Course Active" help="Existing enrolled students can access content." value={course.active} set={(v:boolean)=>set("active",v)}/></div><Field label="Course Status"><select value={course.status} onChange={e=>set("status",e.target.value)}><option value="draft">Draft</option><option value="published">Published</option><option value="archived">Archived</option></select></Field></div>}
function Toggle({label,help,value,set}:any){return <div className="builder-toggle"><div><b>{label}</b>{help&&<small>{help}</small>}</div><Switch checked={!!value} onCheckedChange={set}/></div>}

function NodeEditor({node,update,options,youtubeWarning,setYoutubeWarning}:any){const set=(k:string,v:any)=>update({...node,[k]:v}),lesson=node.node_type==="lesson";const checkYoutube=async()=>{const id=youtubeId(node.video_url||"");if(!id){setYoutubeWarning("Enter a valid YouTube URL.");return}set("video_id",id);try{await api("admin/youtube-check",{url:node.video_url});setYoutubeWarning("");toast.success("This YouTube video is available for embedding.")}catch(e:any){setYoutubeWarning(e.message)}};return <div><div className="lesson-editor-head"><div><span>{node.node_type}{node.lesson_type?` · ${lessonLabels[node.lesson_type as LessonType]}`:""}</span><h2>Edit Content</h2></div><span className={`status-pill ${node.status}`}>{node.status}</span></div><Field label={node.node_type==="module"?"Module Name":"Title"}><input value={node.title} onChange={e=>set("title",e.target.value)}/></Field><Field label="Description"><textarea rows={3} value={node.description} onChange={e=>set("description",e.target.value)}/></Field>{!lesson&&<><Field label="Default access for new classes"><select value={node.access_mode||"code"} onChange={e=>set("access_mode",e.target.value)}><option value="public">Public</option><option value="code">Course code required</option></select></Field><p className="muted">New classes inherit this setting; existing classes keep their chosen access.</p><Field label="Visibility"><select value={node.status} onChange={e=>set("status",e.target.value)}><option value="published">Published</option><option value="draft">Draft</option><option value="hidden">Hidden</option></select></Field></>}{lesson&&<>
  {(node.lesson_type==="youtube"||node.lesson_type==="video")&&<><Field label={node.lesson_type==="youtube"?"YouTube Video URL":"Hosted / Supported Video URL"}><div className="url-check"><input value={node.video_url||""} onChange={e=>{set("video_url",e.target.value);if(node.lesson_type==="youtube")set("video_id",youtubeId(e.target.value))}} placeholder="https://www.youtube.com/watch?v=..."/><button type="button" onClick={checkYoutube}>Check</button></div></Field>{youtubeWarning&&<p className="embed-warning">{youtubeWarning}</p>}{node.video_id&&<div className="video-preview"><iframe src={`https://www.youtube-nocookie.com/embed/${node.video_id}`} title="YouTube preview" allowFullScreen/></div>}<div className="grid two"><Field label="Video Duration"><input value={node.video_duration||""} onChange={e=>set("video_duration",e.target.value)} placeholder="01:20:00"/></Field><Field label="Instructor"><input value={node.instructor||""} onChange={e=>set("instructor",e.target.value)}/></Field></div></>}
  {(node.lesson_type==="pdf"||node.lesson_type==="notes")&&<><Field label={node.lesson_type==="pdf"?"Upload Lecture Sheet PDF":"Upload Note / Document (PDF)"}><MediaUpload kind="coursePdf" value={node.file_id} onChange={v=>set("file_id",v)}/></Field></>}
  {node.lesson_type==="text"&&<Field label="Text Lesson"><textarea rows={14} value={node.body} onChange={e=>set("body",e.target.value)}/></Field>}
  {node.lesson_type==="resource"&&<Field label="External Resource URL"><input type="url" value={node.external_url||""} onChange={e=>set("external_url",e.target.value)}/></Field>}
  {node.lesson_type==="exam"&&<><Field label="Existing Individual MCQ Exam"><select value={node.exam_id||""} onChange={e=>set("exam_id",e.target.value||null)}><option value="">Select an exam</option>{options.exams.map((x:any)=><option key={x.id} value={x.id}>{x.title} · {x.question_count} questions · {x.duration} min</option>)}</select></Field><a className="text-link" href="/admin/exams/new" target="_blank"><Plus size={15}/> Create New Exam</a><ExamSummary item={options.exams.find((x:any)=>x.id===node.exam_id)}/><p className="muted">Set attempt limits in the linked exam. A learner’s code applies to that exam across the course and exam packages.</p></>}
  {node.lesson_type==="package"&&<Field label="Existing Exam Package"><select value={node.package_id||""} onChange={e=>set("package_id",e.target.value||null)}><option value="">Select a package</option>{options.packages.map((x:any)=><option key={x.id} value={x.id}>{x.title} · {x.exam_count} exams</option>)}</select></Field>}
  {node.lesson_type!=="package"&&node.lesson_type!=="exam"&&<Field label="Attach an existing MCQ exam to this class (optional)"><select value={node.exam_id||""} onChange={e=>set("exam_id",e.target.value||null)}><option value="">No exam attached</option>{options.exams.map((x:any)=><option key={x.id} value={x.id}>{x.title} · {x.question_count} questions</option>)}</select></Field>}
  {node.lesson_type!=="package"&&<ResourceEditor resources={node.resources||[]} setResources={(v:any[])=>set("resources",v)}/>}
  <Field label="Class access"><select value={node.access_mode||"code"} onChange={e=>update({...node,access_mode:e.target.value,free_preview:e.target.value==="public"})}><option value="public">Public · anyone can view</option><option value="code">Assigned course code required</option></select></Field>
  <div className="grid two"><Field label="Visibility"><select value={node.status} onChange={e=>set("status",e.target.value)}><option value="published">Published</option><option value="draft">Draft</option><option value="hidden">Hidden</option></select></Field><Field label="Unlock Rule"><select value={node.unlock_rule} onChange={e=>set("unlock_rule",e.target.value)}><option value="immediate">Available immediately</option><option value="previous_lesson">After previous lesson</option><option value="module_complete">After module completion</option><option value="progress">Minimum course progress</option><option value="scheduled">Scheduled</option><option value="manual">Manual unlock</option></select></Field></div>{node.unlock_rule!=="immediate"&&<Field label={node.unlock_rule==="progress"?"Required Progress %":node.unlock_rule==="scheduled"?"Unlock Date & Time":"Unlock Reference / Value"}><input value={node.unlock_value||""} onChange={e=>set("unlock_value",e.target.value)}/></Field>}<div className="access-switches">{(node.lesson_type==="pdf"||node.lesson_type==="notes")&&<Toggle label="Download Allowed" value={node.download_allowed} set={(v:boolean)=>set("download_allowed",v)}/>}</div>
  </>}</div>}
function ResourceEditor({resources,setResources}:any){return <div className="resource-editor"><div className="panel-title"><div><h3>Additional PDFs / Resources</h3><p>Attach multiple supporting files.</p></div><button type="button" className="btn small outline" onClick={()=>setResources([...resources,{id:crypto.randomUUID(),title:"",description:"",file_id:null,download_allowed:false,free_preview:false}])}><Plus/> Add PDF</button></div>{resources.map((r:any,i:number)=><div className="resource-row" key={r.id}><Field label="PDF Title"><input value={r.title} onChange={e=>setResources(resources.map((x:any,j:number)=>j===i?{...x,title:e.target.value}:x))}/></Field><Field label="Description"><input value={r.description} onChange={e=>setResources(resources.map((x:any,j:number)=>j===i?{...x,description:e.target.value}:x))}/></Field><MediaUpload kind="coursePdf" value={r.file_id} onChange={v=>setResources(resources.map((x:any,j:number)=>j===i?{...x,file_id:v}:x))}/><div className="resource-options"><label><input type="checkbox" checked={r.download_allowed} onChange={e=>setResources(resources.map((x:any,j:number)=>j===i?{...x,download_allowed:e.target.checked}:x))}/> Download</label><label><input type="checkbox" checked={r.free_preview} onChange={e=>setResources(resources.map((x:any,j:number)=>j===i?{...x,free_preview:e.target.checked}:x))}/> Free preview</label><button onClick={()=>setResources(resources.filter((_:any,j:number)=>j!==i))}><Trash2/></button></div></div>)}</div>}
function ExamSummary({item}:any){if(!item)return null;return <div className="exam-summary"><b>{item.title}</b><span>{item.question_count} questions</span><span>{item.total_marks} marks</span><span>{item.duration} minutes</span><span>Negative: {item.negative_mark/100}</span><span>Pass: {item.pass_mark/100}</span><span>{item.status}</span></div>}
function CoursePreview({course,nodes,mode}:any){const first=nodes.find((n:any)=>n.node_type==="lesson");const modules=nodes.filter((n:any)=>n.node_type==="module");return <div className={`course-preview-frame ${mode}`}><div className="course-preview-app"><main><div className="preview-media">{first?.video_id?<iframe src={`https://www.youtube-nocookie.com/embed/${first.video_id}`} title="Preview" allowFullScreen/>:first?.file_id?<div><FileText size={52}/><b>In-site PDF Viewer</b><span>Scroll · Zoom · Fullscreen</span></div>:<div><CirclePlay size={56}/><b>Select a lesson to begin</b></div>}</div><div className="preview-lesson-copy"><span>{course.name||"Course Name"}</span><h2>{first?.title||"Your first lesson"}</h2><p>{first?.description||"Lesson description will appear here."}</p><div className="preview-nav"><button>Previous Lesson</button><button className="complete">Mark as Complete</button><button>Next Lesson</button></div></div></main><aside><div><b>Course Progress</b><span>0%</span></div><Progress value={0}/>{modules.map((m:any)=><section key={m.id}><h3>{m.title}</h3>{nodes.filter((n:any)=>n.parent_id===m.id).flatMap((c:any)=>c.node_type==="lesson"?[c]:nodes.filter((n:any)=>n.parent_id===c.id)).map((l:any)=><button key={l.id}><span>{l.lesson_type==="youtube"?<CirclePlay/>:l.lesson_type==="exam"?<ListChecks/>:<FileText/>}</span>{l.title}</button>)}</section>)}</aside></div></div>}
function parse(value:any,fallback:any){try{return typeof value==="string"?JSON.parse(value):value??fallback}catch{return fallback}}
