'use client';
import {useEffect,useState} from 'react';
import {toast} from 'sonner';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {AlertDialog,AlertDialogContent,AlertDialogHeader,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel,AlertDialogAction} from '@/components/ui/alert-dialog';
import {Table,TableBody,TableCell,TableHead,TableHeader,TableRow} from '@/components/ui/table';
import {Pagination,PaginationContent,PaginationItem,PaginationPrevious,PaginationNext} from '@/components/ui/pagination';
import {Skeleton} from '@/components/ui/skeleton';
import {Empty,EmptyHeader,EmptyTitle,EmptyDescription} from '@/components/ui/empty';
export const money=(n:number)=>'৳'+(Number(n||0)/100).toLocaleString('en-BD',{maximumFractionDigits:2});
export const date=(n:number)=>n?new Intl.DateTimeFormat('en-US',{dateStyle:'medium',timeStyle:'short',hour12:true,timeZone:'Asia/Dhaka'}).format(n):'—';
export const duration=(n:number)=>`${Math.floor(n/60000)}m ${Math.floor(n/1000)%60}s`;
export const deliveryNames:Record<string,string>={sundarban:'Sundarban Courier',dhaka:'Home Delivery Within Dhaka',outside:'Home Delivery Outside Dhaka'};
export async function api(path:string,body?:any,method?:string):Promise<any>{const r=await fetch('/api/'+path,{method:method||(body?'POST':'GET'),headers:{'X-LVA-Request':'1',...(body?{'Content-Type':'application/json'}:{})},...(body?{body:JSON.stringify(body)}:{})});let d:any;try{d=await r.json()}catch{throw Error('The service is temporarily unavailable. Please try again.')}if(!r.ok)throw Object.assign(Error(d.error||'Request failed'),{status:r.status});return d}
export function useData(path:string,initialData:any=null){const [data,setData]=useState<any>(initialData),[error,setError]=useState(''),[revision,setRevision]=useState(0);useEffect(()=>{if(initialData!==null&&revision===0)return;let live=true;setError('');api(path).then(d=>{if(live)setData(d)}).catch(e=>{if(live)setError(e.message)});return()=>{live=false}},[path,revision]);return{data,error,reload:()=>setRevision(v=>v+1)}}
export function Field({label,children,...p}:any){return <label className="field"><span>{label}</span>{children||<input {...p}/>}</label>}
export function Choice({value,onChange,options,label}:any){return <Select value={String(value)} onValueChange={onChange}><SelectTrigger className="choice" aria-label={label}><SelectValue/></SelectTrigger><SelectContent>{options.map((o:any)=><SelectItem key={typeof o==='string'?o:o.value} value={typeof o==='string'?o:String(o.value)}>{typeof o==='string'?o:o.label}</SelectItem>)}</SelectContent></Select>}
export function Confirm({open,onOpenChange,title,description,onConfirm,action='Confirm'}:any){return <AlertDialog open={open} onOpenChange={onOpenChange}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>{title}</AlertDialogTitle><AlertDialogDescription>{description}</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Cancel</AlertDialogCancel><AlertDialogAction onClick={onConfirm}>{action}</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>}
export function EmptyState({title='Nothing here yet',children}:any){return <Empty className="empty-state"><EmptyHeader><EmptyTitle>{title}</EmptyTitle><EmptyDescription>{children}</EmptyDescription></EmptyHeader></Empty>}
export function Loading(){return <div className="loading" role="status" aria-label="Loading"><Skeleton className="h-8 w-2/3"/><Skeleton className="h-32 w-full"/></div>}
export function ErrorBox({error}:any){return error?<p className="error" role="alert"><span className="error-mark" aria-hidden="true">!</span><strong>Error:</strong> {error}</p>:null}
export function DataTable({headers,rows}:any){return <Table><TableHeader><TableRow>{headers.map((h:string)=><TableHead key={h}>{h}</TableHead>)}</TableRow></TableHeader><TableBody>{rows.map((r:any[],i:number)=><TableRow key={i}>{r.map((c,j)=><TableCell key={j}>{c}</TableCell>)}</TableRow>)}</TableBody></Table>}
export function Pages({page,total,setPage}:any){return <div className="paging"><span>{total.toLocaleString()} records · Page {page} of {Math.max(1,Math.ceil(total/50))}</span><Pagination><PaginationContent><PaginationItem><PaginationPrevious href="#" aria-disabled={page<=1} onClick={e=>{e.preventDefault();if(page>1)setPage(page-1)}}/></PaginationItem><PaginationItem><PaginationNext href="#" aria-disabled={page*50>=total} onClick={e=>{e.preventDefault();if(page*50<total)setPage(page+1)}}/></PaginationItem></PaginationContent></Pagination></div>}
export function ActionButton({action,children,className='btn',...props}:any){const [busy,setBusy]=useState(false);return <button {...props} className={className} disabled={busy||props.disabled} onClick={async()=>{setBusy(true);try{await action()}catch(e:any){toast.error(e.message)}finally{setBusy(false)}}}>{busy?'Please wait…':children}</button>}
export function cash(s:string){if(!/^\d+(\.\d{1,2})?$/.test(s))throw Error('Enter an amount with up to two decimal places.');const [a,b='']=s.split('.');return Number(a)*100+Number(b.padEnd(2,'0'))}
